config/routes.rb
Rails.application.routes.draw do
  resources :data_pendidikan_agama_katolik
  devise_for :users

  scope "/mengelola" do
  	resources :users
  end

  get 'beranda/index'
  resources :data_keagamaan_katolik
  resources :laporan_penyuluh_agama_katolik
  resources :peran
  resources :users
  root 'beranda#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/peran.rb
class Peran < ApplicationRecord
	has_many :users
end

app/controllers/peran_controller.rb
class PeranController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /peran
  # GET /peran.json
  def index
    @peran = Peran.all
  end

  # GET /peran/1
  # GET /peran/1.json
  def show
    if @peran.users.length == 0
      @user_terhubung = "Tidak ada yang terhubung"
    else
      @user_terhubung = @peran.users.map(&:nama_lengkap).join(", ")
    end
  end

  # GET /peran/new
  def new
  end

  # GET /peran/1/edit
  def edit
  end

  # POST /peran
  # POST /peran.json
  def create

    respond_to do |format|
      if @peran.save
        format.html { redirect_to @peran, notice: 'Peran was successfully created.' }
        format.json { render :show, status: :created, location: @peran }
      else
        format.html { render :new }
        format.json { render json: @peran.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peran/1
  # PATCH/PUT /peran/1.json
  def update
    respond_to do |format|
      if @peran.update(peran_params)
        format.html { redirect_to @peran, notice: 'Peran was successfully updated.' }
        format.json { render :show, status: :ok, location: @peran }
      else
        format.html { render :edit }
        format.json { render json: @peran.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peran/1
  # DELETE /peran/1.json
  def destroy
    @peran.destroy
    respond_to do |format|
      format.html { redirect_to peran_index_url, notice: 'Peran was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def peran_params
      params.require(:peran).permit(:nama_peran, :keterangan)
    end
end

app/helpers/peran_helper.rb
module PeranHelper
end

app/views/peran/_form.html.erb
<%= form_with(model: peran, local: true) do |form| %>
  <% if peran.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(peran.errors.count, "error") %> prohibited this peran from being saved:</h2>

      <ul>
      <% peran.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nama_peran %>
    <%= form.text_field :nama_peran %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/peran/edit.html.erb
<h1>Editing Peran</h1>

<%= render 'form', peran: @peran %>

<%= link_to 'Show', @peran %> |
<%= link_to 'Back', peran_index_path %>

app/views/peran/index.html.erb
<h1>Peran</h1>

<table>
  <thead>
    <tr>
      <th>Nama peran</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peran.each do |peran| %>
      <tr>
        <td><%= peran.nama_peran %></td>
        <td><%= link_to 'Show', peran %></td>
        <td><%= link_to 'Edit', edit_peran_path(peran) %></td>
        <td><%= link_to 'Destroy', peran, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Peran', new_peran_path %>

app/views/peran/new.html.erb
<h1>New Peran</h1>

<%= render 'form', peran: @peran %>

<%= link_to 'Back', peran_index_path %>

app/views/peran/show.html.erb
<p>
  <strong>Nama peran:</strong>
  <%= @peran.nama_peran %>
</p>

<p>
  <strong>User yang terhubung:</strong>
  <%= @user_terhubung %>
</p>

<%= link_to 'Edit', edit_peran_path(@peran) %> |
<%= link_to 'Back', peran_index_path %>