config/routes.rb
Rails.application.routes.draw do
  resources :data_pendidikan_agama_katolik
  devise_for :users

  scope "/mengelola" do
  	resources :users
  end

  get 'beranda/index'
  resources :data_keagamaan_katolik
  resources :laporan_penyuluh_agama_katolik
  resources :peran
  resources :users
  root 'beranda#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/laporan_penyuluh_agama_katolik.rb
class LaporanPenyuluhAgamaKatolik < ApplicationRecord
	validates :judul, length: { minimum: 5 }
	validates :keterangan, length: { minimum: 9 }
	belongs_to :user
end

app/controllers/laporan_penyuluh_agama_katolik_controller.rb
class LaporanPenyuluhAgamaKatolikController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  load_and_authorize_resource

  # GET /laporan_penyuluh_agama_katolik
  # GET /laporan_penyuluh_agama_katolik.json
  def index
    @laporan_penyuluh_agama_katolik = LaporanPenyuluhAgamaKatolik.all
  end

  # GET /laporan_penyuluh_agama_katolik/1
  # GET /laporan_penyuluh_agama_katolik/1.json
  def show
  end

  # GET /laporan_penyuluh_agama_katolik/new
  def new
  end

  # GET /laporan_penyuluh_agama_katolik/1/edit
  def edit
  end

  # POST /laporan_penyuluh_agama_katolik
  # POST /laporan_penyuluh_agama_katolik.json
  def create
    @laporan_penyuluh_agama_katolik.user_id = current_user.id

    respond_to do |format|
      if @laporan_penyuluh_agama_katolik.save
        format.html { redirect_to @laporan_penyuluh_agama_katolik, notice: 'Laporan penyuluh agama katolik was successfully created.' }
        format.json { render :show, status: :created, location: @laporan_penyuluh_agama_katolik }
      else
        format.html { render :new }
        format.json { render json: @laporan_penyuluh_agama_katolik.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laporan_penyuluh_agama_katolik/1
  # PATCH/PUT /laporan_penyuluh_agama_katolik/1.json
  def update
    respond_to do |format|
      if @laporan_penyuluh_agama_katolik.update(laporan_penyuluh_agama_katolik_params)
        format.html { redirect_to @laporan_penyuluh_agama_katolik, notice: 'Laporan penyuluh agama katolik was successfully updated.' }
        format.json { render :show, status: :ok, location: @laporan_penyuluh_agama_katolik }
      else
        format.html { render :edit }
        format.json { render json: @laporan_penyuluh_agama_katolik.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laporan_penyuluh_agama_katolik/1
  # DELETE /laporan_penyuluh_agama_katolik/1.json
  def destroy
    @laporan_penyuluh_agama_katolik.destroy
    respond_to do |format|
      format.html { redirect_to laporan_penyuluh_agama_katolik_index_url, notice: 'Laporan penyuluh agama katolik was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def laporan_penyuluh_agama_katolik_params
      params.require(:laporan_penyuluh_agama_katolik).permit(:judul, :keterangan, :tautan, :user_id)
    end
end

app/helpers/laporan_penyuluh_agama_katolik_helper.rb
module LaporanPenyuluhAgamaKatolikHelper
end

app/views/laporan_penyuluh_agama_katolik/_form.html.erb
<%= form_with(model: laporan_penyuluh_agama_katolik, local: true) do |form| %>
  <% if laporan_penyuluh_agama_katolik.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(laporan_penyuluh_agama_katolik.errors.count, "error") %> prohibited this laporan_penyuluh_agama_katolik from being saved:</h2>

      <ul>
      <% laporan_penyuluh_agama_katolik.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :judul %>
    <%= form.text_field :judul %>
  </div>

  <div class="field">
    <%= form.label :keterangan %>
    <%= form.text_field :keterangan %>
  </div>

  <div class="field">
    <%= form.label :tautan %>
    <%= form.text_field :tautan %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/laporan_penyuluh_agama_katolik/edit.html.erb
<h1>Mengedit Laporan Penyuluh Agama Katolik</h1>

<%= render 'form', laporan_penyuluh_agama_katolik: @laporan_penyuluh_agama_katolik %>

<%= link_to 'Show', @laporan_penyuluh_agama_katolik %> |
<%= link_to 'Back', laporan_penyuluh_agama_katolik_index_path %>

app/views/laporan_penyuluh_agama_katolik/index.html.erb
<h1>Daftar Laporan Penyuluh Agama Katolik</h1>

<table>
  <thead>
    <tr>
      <th>Judul</th>
      <th>Keterangan</th>
      <th>Tautan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @laporan_penyuluh_agama_katolik.each do |laporan_penyuluh_agama_katolik| %>
      <tr>
        <td><%= laporan_penyuluh_agama_katolik.judul %></td>
        <td><%= laporan_penyuluh_agama_katolik.keterangan %></td>
        <td><%= laporan_penyuluh_agama_katolik.tautan %></td>
        <td><%= link_to 'Show', laporan_penyuluh_agama_katolik %></td>
        <td><%= link_to 'Edit', edit_laporan_penyuluh_agama_katolik_path(laporan_penyuluh_agama_katolik) %></td>
        <td><%= link_to 'Destroy', laporan_penyuluh_agama_katolik, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Laporan Penyuluh Agama Katolik', new_laporan_penyuluh_agama_katolik_path %>

app/views/laporan_penyuluh_agama_katolik/new.html.erb
<h1>Membuat Laporan Penyuluh Agama Katolik</h1>

<%= render 'form', laporan_penyuluh_agama_katolik: @laporan_penyuluh_agama_katolik %>

<%= link_to 'Batal', laporan_penyuluh_agama_katolik_index_path %>

app/views/laporan_penyuluh_agama_katolik/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Judul:</strong>
  <%= @laporan_penyuluh_agama_katolik.judul %>
</p>

<p>
  <strong>Keterangan:</strong>
  <%= @laporan_penyuluh_agama_katolik.keterangan %>
</p>

<p>
  <strong>Tautan:</strong>
  <%= @laporan_penyuluh_agama_katolik.tautan %>
</p>

<%= link_to 'Edit', edit_laporan_penyuluh_agama_katolik_path(@laporan_penyuluh_agama_katolik) %> |
<%= link_to 'Batal', laporan_penyuluh_agama_katolik_index_path %>