config/routes.rb
Rails.application.routes.draw do
  resources :data_pendidikan_agama_katolik
  devise_for :users

  scope "/mengelola" do
  	resources :users
  end

  get 'beranda/index'
  resources :data_keagamaan_katolik
  resources :laporan_penyuluh_agama_katolik
  resources :peran
  resources :users
  root 'beranda#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/data_pendidikan_agama_katolik.rb
class DataPendidikanAgamaKatolik < ApplicationRecord
	validates :judul, length: { minimum: 5 }
	validates :keterangan, length: { minimum: 9 }
	belongs_to :user
end

app/controllers/data_pendidikan_agama_katolik_controller.rb
class DataPendidikanAgamaKatolikController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  load_and_authorize_resource

  # GET /data_pendidikan_agama_katolik
  # GET /data_pendidikan_agama_katolik.json
  def index
    @data_pendidikan_agama_katolik = DataPendidikanAgamaKatolik.all
  end

  # GET /data_pendidikan_agama_katolik/1
  # GET /data_pendidikan_agama_katolik/1.json
  def show
  end

  # GET /data_pendidikan_agama_katolik/new
  def new
  end

  # GET /data_pendidikan_agama_katolik/1/edit
  def edit
  end

  # POST /data_pendidikan_agama_katolik
  # POST /data_pendidikan_agama_katolik.json
  def create
    @data_pendidikan_agama_katolik.user_id = current_user.id

    respond_to do |format|
      if @data_pendidikan_agama_katolik.save
        format.html { redirect_to @data_pendidikan_agama_katolik, notice: 'Data pendidikan agama katolik was successfully created.' }
        format.json { render :show, status: :created, location: @data_pendidikan_agama_katolik }
      else
        format.html { render :new }
        format.json { render json: @data_pendidikan_agama_katolik.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_pendidikan_agama_katolik/1
  # PATCH/PUT /data_pendidikan_agama_katolik/1.json
  def update
    respond_to do |format|
      if @data_pendidikan_agama_katolik.update(data_pendidikan_agama_katolik_params)
        format.html { redirect_to @data_pendidikan_agama_katolik, notice: 'Data pendidikan agama katolik was successfully updated.' }
        format.json { render :show, status: :ok, location: @data_pendidikan_agama_katolik }
      else
        format.html { render :edit }
        format.json { render json: @data_pendidikan_agama_katolik.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_pendidikan_agama_katolik/1
  # DELETE /data_pendidikan_agama_katolik/1.json
  def destroy
    @data_pendidikan_agama_katolik.destroy
    respond_to do |format|
      format.html { redirect_to data_pendidikan_agama_katolik_index_url, notice: 'Data pendidikan agama katolik was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    # Never trust parameters from the scary internet, only allow the white list through.
    def data_pendidikan_agama_katolik_params
      params.require(:data_pendidikan_agama_katolik).permit(:judul, :keterangan, :tautan)
    end
end

app/helpers/data_pendidikan_agama_katolik_helper.rb
module DataPendidikanAgamaKatolikHelper
end

app/views/data_pendidikan_agama_katolik/_form.html.erb
<%= form_with(model: data_pendidikan_agama_katolik, local: true) do |form| %>
  <% if data_pendidikan_agama_katolik.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(data_pendidikan_agama_katolik.errors.count, "error") %> prohibited this data_pendidikan_agama_katolik from being saved:</h2>

      <ul>
      <% data_pendidikan_agama_katolik.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :judul %>
    <%= form.text_field :judul %>
  </div>

  <div class="field">
    <%= form.label :keterangan %>
    <%= form.text_field :keterangan %>
  </div>

  <div class="field">
    <%= form.label :tautan %>
    <%= form.text_field :tautan %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/data_pendidikan_agama_katolik/edit.html.erb
<h1>Editing Data Pendidikan Agama Katolik</h1>

<%= render 'form', data_pendidikan_agama_katolik: @data_pendidikan_agama_katolik %>

<%= link_to 'Show', @data_pendidikan_agama_katolik %> |
<%= link_to 'Back', data_pendidikan_agama_katolik_index_path %>

app/views/data_pendidikan_agama_katolik/index.html.erb
<h1>Data Pendidikan Agama Katolik</h1>

<table>
  <thead>
    <tr>
      <th>Judul</th>
      <th>Keterangan</th>
      <th>Tautan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_pendidikan_agama_katolik.each do |data_pendidikan_agama_katolik| %>
      <tr>
        <td><%= data_pendidikan_agama_katolik.judul %></td>
        <td><%= data_pendidikan_agama_katolik.keterangan %></td>
        <td><%= data_pendidikan_agama_katolik.tautan %></td>
        <td><%= data_pendidikan_agama_katolik.user.nama_lengkap %></td>
        <td><%= link_to 'Show', data_pendidikan_agama_katolik %></td>
        <td><%= link_to 'Edit', edit_data_pendidikan_agama_katolik_path(data_pendidikan_agama_katolik) %></td>
        <td><%= link_to 'Destroy', data_pendidikan_agama_katolik, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Data Pendidikan Agama Katolik', new_data_pendidikan_agama_katolik_path %>

app/views/data_pendidikan_agama_katolik/new.html.erb
<h1>New Data Pendidikan Agama Katolik</h1>

<%= render 'form', data_pendidikan_agama_katolik: @data_pendidikan_agama_katolik %>

<%= link_to 'Back', data_pendidikan_agama_katolik_index_path %>

app/views/data_pendidikan_agama_katolik/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Judul:</strong>
  <%= @data_pendidikan_agama_katolik.judul %>
</p>

<p>
  <strong>Keterangan:</strong>
  <%= @data_pendidikan_agama_katolik.keterangan %>
</p>

<p>
  <strong>Tautan:</strong>
  <%= @data_pendidikan_agama_katolik.tautan %>
</p>

<p>
  <strong>Pembuat:</strong>
  <%= @data_pendidikan_agama_katolik.user.nama_lengkap %>
</p>

<%= link_to 'Edit', edit_data_pendidikan_agama_katolik_path(@data_pendidikan_agama_katolik) %> |
<%= link_to 'Back', data_pendidikan_agama_katolik_index_path %>